enum MDCmd {
  // v2
  thirdLogin('zs_third_login'),
  bindThird('zs_bind_third'),
  bindMobile('zs_bind_mobile'),
  bindGuest('zs_bind_guest'),
  thirdSiqt('zs_third_siqt'),
  popUp('zs_pop_up'),
  remind('zs_remind'),
  popUpReport('zs_pop_up_report'),
  remindReport('zs_remind_report'),
  videoDurationReport('zs_video_duration_report'),
  checkCourse('zs_check_course'),
  oss('zs_oss'),
  zyList('zs_zy_list'),
  zyLog('zs_zy_log'),
  zyPublic('zs_zy_public'),
  zySubmit('zs_zy_submit'),

// v1
  memberInfo('zs_member_info'),
  login('zs_login'),
  courseDetail('zs_course_detail'),
  myCourses('zs_my_courses'),
  home('zs_home'),
  sendCode('zs_send_code'),
  forgotPwd('zs_forgot_pwd'),
  loginGuest('zs_login_guest'),
  version('zs_version'),
  modifyNick('zs_modify_nick'),
  modifyAvatar('zs_modify_avatar'),
  logout('zs_logout'),
  modifyPwd('zs_modify_pwd'),
  logoff('zs_logoff'),
  courseOrders('zs_course_orders'),
  collects('zs_collects'),
  feedback('zs_feedback'),
  iapProducts('zs_iap_products'),
  iapOrders('zs_iap_orders'),
  iapCreateOrder('zs_iap_create_order'),
  iapVerifyOrder('zs_iap_verify_order'),
  courseList('zs_course_list'),
  dateCourses('zs_date_courses'),
  cancelYdy('zs_cancel_ydy'),
  prebokYdy('zs_prebok_ydy'),
  monthDate('zs_month_date'),
  joinGk('zs_join_gk'),
  ossUrl('zs_oss_url'),
  courseFiles('zs_course_files'),
  courseFavorite('zs_course_favorite'),
  courseConfirmIos('zs_course_confirm_ios'),
  coursPay('zs_cours_pay'),
  playback('zs_playback'),
  live('zs_live');

  const MDCmd(this.value);

  final String value;
}